version: '3'

services:
  # Golang application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./internal/config/.env
    volumes:
      - .:/usr/src/app

  # PostgreSQL database
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_scripts:
  postgres-data:
